// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Proof } from "@gribi/evm-rootsystem/Structs.sol";

/**
 * @title IGribiSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IGribiSystem {
  function setRootSystemAddress(address rootSystemAddress) external;

  function registerModules() external;

  function execute(uint256 id, bytes memory data) external;

  function execute(uint256 id, bytes memory data, Proof memory proof) external;
}
